AWSTemplateFormatVersion:  "2010-09-09"
Description:  VPCとEC2を作って起動できるかの確認。


  #------#外部入力が必要な箇所用------
Parameters: 
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: "AWS::EC2::KeyPair::KeyName"

  DBmasterName:
    Description: DBmasterName
    Type: String

  DBmasterPassword:
    Description: DBMasterPassword
    NoEcho: true #入力時パスワードの文字を隠すことが出来るか
    Type: String
  
  MyIPAdoress:
    Description: IPAdoless(123.456.xxx.xxx/32)
    Type: String

Resources: 

  #------VPC-------

  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Value: AWS-study-vpc
          Key: Name
      InstanceTenancy: default

  #------PublicSubnet------

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpc
      AvailabilityZone:  !Select [0, !GetAZs ''] 
      CidrBlock: 10.0.0.0/20
      MapPublicIpOnLaunch: true
      Tags:
        - Value:  AWS-Study-PublicSubnet1 
          Key: Name
  
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:  !Ref vpc
      AvailabilityZone:  !Select [1, !GetAZs '']
      CidrBlock: 10.0.16.0/20
      MapPublicIpOnLaunch: true
      Tags:
        - Key:  Name
          Value:  AWS-Study-PublicSubnet2

  #-------PrivateSubnet------

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:  !Ref vpc
      AvailabilityZone:  !Select [0, !GetAZs '']
      CidrBlock: 10.0.128.0/20
      MapPublicIpOnLaunch: false
      Tags:
        - Key:  Name
          Value:  AWS-Study-PrivateSubnet1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:  !Ref vpc
      AvailabilityZone:  !Select [1, !GetAZs '']
      CidrBlock: 10.0.144.0/20
      MapPublicIpOnLaunch: false
      Tags:
        - Key:  Name
          Value:  AWS-Study-PrivateSubnet2

  #------DBSubnetGroup------
  rdsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: rdsDBSubnetGroup
      DBSubnetGroupName: DBSubnetGroup
      SubnetIds:
        -  !Ref PrivateSubnet1
        -  !Ref PrivateSubnet2


  #------SecurityGroup------

  EC2InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGrouptest
      VpcId:  !Ref vpc
      SecurityGroupIngress: 
        - IpProtocol: tcp 
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIPAdoress
      Tags:
        - Key: Name
          Value:  AWS-Study-EC2-SG

  InstanceSecurityGroupRuleHttp: 
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:  !Ref EC2InstanceSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0

  InstanceSecurityGroupRuleHttps:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:  !Ref EC2InstanceSecurityGroup
      IpProtocol:  tcp
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0

  InstanceSecurityGroupRulecustomTCP:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:  !Ref EC2InstanceSecurityGroup
      IpProtocol:  tcp
      FromPort: 8080
      ToPort: 8080
      CidrIp: 0.0.0.0/0

  #------RDSSeculityGroup------
  rdsDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:  !Ref vpc
      GroupDescription: rdsDBSecurityGroup
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId:  !Ref EC2InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: AWS-Study-db-sg

  #------IGW-------

  myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: AWS-Study-EC2-IGW

  myInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:  !Ref myInternetGateway
      VpcId:  !Ref vpc

  MyEC2EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: AWS-Study-EIP 

  #------NatGateway------

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:  !GetAtt  MyEC2EIP.AllocationId
      SubnetId:  !Ref PublicSubnet1
      Tags:
        - Key:  Name
          Value:  AWS-Study-NatGateway

  #------RouteTable------

  myRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  !Ref vpc
      Tags:
        - Key: Name
          Value: AWS-Study-RouteTable

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref myRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref myRouteTable
      SubnetId: !Ref PublicSubnet2

  myRoute:
    Type: AWS::EC2::Route
    DependsOn: 
      - myInternetGatewayAttachment
    Properties:
      RouteTableId: !Ref myRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref myInternetGateway

  #------EC2------

  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0228232d282f16465 
      InstanceType: t3.micro
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        -  !Ref EC2InstanceSecurityGroup 
      KeyName:  !Ref KeyName
      Tags:
        - Key: Name
          Value: AWS-Study-EC2Instance

  #-------RDS-------

  Datebase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20 #ストレージ量
      MaxAllocatedStorage: 1000
      DBInstanceClass: db.t4g.micro
      AvailabilityZone:  !Select [0, !GetAZs '']
      BackupRetentionPeriod: 1
      DBInstanceIdentifier: aws-study-rds #RDSインスタンスの名前（DBインスタンス識別子）
      DBName: awsstudydb #データベースの名前
      DBSubnetGroupName:  !Ref rdsDBSubnetGroup
      Engine: mysql
      EngineVersion: 8.0.39
      MasterUsername:  !Ref DBmasterName
      MasterUserPassword:  !Ref DBmasterPassword
      PubliclyAccessible: false
      StorageEncrypted: true
      StorageType: gp3
      VPCSecurityGroups:
        -  !Ref rdsDBSecurityGroup
      Tags:
        - Key: name
          Value: AWS-Study-RDS
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot

  
  #------TargetGroup------
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: instance
      Name: aws-study-tg
      Protocol: HTTP
      Port: 80
      VpcId:  !Ref vpc
      ProtocolVersion: HTTP1
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      HealthCheckPort: traffic-port
      HealthCheckIntervalSeconds: 30
      Matcher:
        HttpCode: '200,300,301'
      Targets:
        - Id:  !Ref myEC2Instance
          Port: 80
        - Id:  !Ref myEC2Instance
          Port: 8080
      Tags:
        - Key: Name
          Value: AWS-Study-tg

  #------ALB------
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: aws-study-alb
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets:
      - !Ref PublicSubnet1
      - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref EC2InstanceSecurityGroup
      
  #-------ListenerLule-------
  ALBlistener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Protocol: HTTP
      Port: 80
      LoadBalancerArn:  !Ref ALB
      DefaultActions:
        - Type: forward #ここはAWS::~ではなく、あくまでアクションのタイプ
          TargetGroupArn:  !Ref TargetGroup
      